env:
  node: true
extends:
  - 'airbnb-base'
parserOptions:
  ecmaVersion: 2020
rules:
  no-console: 0
  import/extensions: 0
  import/prefer-default-export: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  quote-props: 0
  no-use-before-define: 0