name: hexlet-check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: frontend-project-lvl2 project check
        uses: Vikman88/frontend-project-lvl2@master